# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'

  - script: pip install -r requirements/base.txt && pip install .
    displayName: 'Install tutor'

  - script: |
      tutor config save --silent \
        --set ACTIVATE_NOTES=true \
        --set ACTIVATE_XQUEUE=true \
        --set LMS_HOST=localhost
    displayName: 'Configure tutor'

  - script: tutor local pullimages
    displayName: 'Pull docker images'

  - script: tutor local databases
    displayName: 'Initialize databases'

  - script: tutor local start -d
    displayName: 'Start edX server'

  - script: curl -v http://localhost/
    displayName: 'Run curl command to confirm tutor is running'

  - script: |
      docker-compose -f $(tutor config printroot)/env/local/docker-compose.yml \
      --project-name tutor_local \
      run --rm \
      -v $(pwd)/tests/fixtures/users.json:/openedx/edx-platform/users.json \
      lms \
        bash -e -c \
          './manage.py lms --settings=tutor.production loaddata users.json'
    displayName: 'Create initial users to be used in tests'

  - script: |
      docker build tests/e2e -t cypress:tutor
    displayName: 'Build cypress e2e tests docker image'

  - script: |
      docker run --rm \
        --name cypress \
        --network host \
        -e CYPRESS_baseUrl=http://localhost:80 \
        cypress:tutor \
        npx cypress run
    displayName: 'Run cypress e2e tests'

  - script: |
      set +e
      set -x
      ls -lR $(tutor config printroot)/data/logs
      cat $(tutor config printroot)/data/logs/lms/edx.log
      cat $(tutor config printroot)/data/logs/lms/tracking.log
      cat $(tutor config printroot)/data/logs/cms/edx.log
      cat $(tutor config printroot)/data/logs/cms/tracking.log
      cat $(tutor config printroot)/data/logs/nginx/access.log
      cat $(tutor config printroot)/data/logs/nginx/error.log
    displayName: 'Have a look at log files'
